#!/usr/bin/env bash
#Custom 404 page that contains the string Ceci n'est pas une page.
#    The page must return an HTTP 404 error code
#    The page must contain the string Ceci n'est pas une page
#    Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new Ubuntu machine to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "19i $new_string" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
location_error="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _;/a $location_error" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
