#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to:
# Configure Nginx so that its HTTP response contains a custom header
#   The name of the custom HTTP header must be
#   Value of the header is the hostname of the server Nginx running on

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "19i $new_string" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
location_error="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _;/a $location_error" /etc/nginx/sites-available/default
header="\\\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "19i $header" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
