#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
#   Distribute requests using a roundrobin algorithm


sudo apt-get -y update
sudo apt-get -y install haproxy

sudo echo "Set ENABLED to 1 if you want the init script to start haproxy.
ENABLED=1" >> /etc/default/haproxy

sudo echo "frontend site_front
	bind *:80
	default_backend site_back
" >> /etc/haproxy/haproxy.cfg

sudo echo "backend site_back
	balance roundrobin
	mode tcp
	server 1248-web-01 104.196.213.138:80 check
	server 1248-web-02 3.80.40.75:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
