#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
#   Distribute requests using a roundrobin algorithm


sudo apt-get -y update
sudo apt-get -y install haproxy
echo "frontend site_front
	bind *:80
	stats uri /haproxy?stats
	default_backend site_back
" >> /etc/haproxy/haproxy.cfg
echo "backend site_back
	balance roundrobin
	server 1248-web-01 104.196.213.138 check
	server 1248-web-02 3.80.40.75 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
