#!/usr/bin/env bash
# Nginx must be running, and listening on port 80

sudo sed 's!listen 8080 default_server!listen 80 default_server!' /etc/nginx/sites-enabled/default
sudo sed 's!listen [::]:8080 default_server!listen [::]:80 default_server!' /etc/nginx/sites-enabled/default
sudo service nginx restart
