#!/usr/bin/env bash
# Nginx must be running, and listening on port 80
sudo sed -i 's!listen 8080 default_server!listen 80 default_server!' /etc/nginx/sites-enabled/default
sudo sed -i 's!8080 default_server ipv6only=on!80 default_server!' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx stop
