#!/usr/bin/env bash
#Bash script that displays a list of currently running processes
# show all processes for all users, including those without TTY
# Display in a user-oriented format
# Show process hierarchy
ps axuf
