#!/usr/bin/env bash
# this thing does a lot of things
echo $$ > "/var/run/holbertonscript.pid"

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid"
trap "exit" SIGQUIT
trap "rm /var/run/holbertonscript.pid"
trap "exit" SIGTERM
while true
do
   echo "To infinity and beyond"
   sleep 2
done

