#!/usr/bin/env bash
# displays numbers from 1 to 100 replacing with Fizz  multiples of 3,
# buzz mults of 5 and FizzBuzz mults of 3 and 5

for i in {1..100}
do
   if (( i % 15 == 0 ))
   then
      echo "FizzBuzz"
   elif (( i % 5 == 0 ))
   then
      echo "Buzz"
   elif (( i % 3 == 0 ))
   then
      echo "Fizz"
   else
      echo "$i"
   fi
done
