#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user
# nginx must be listening on all active IPs on port 8080
pkill -9 apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
